mirth-lang/mirth

.vscode/tasks.json, bootstrap/mirth.py
Sligthly change format of error messages in bootstrap to improve the error reporting in vscode.
=> Provide a default build task for vscode

mirth.mth, mirth0.c
This design was not beneficial and was causing problems on Windows, which is less lenient about file descriptors. So now the `print!` and `trace!` words always print to stdout / stderr, rather than depending on mutable file descriptor variables.
=> Remove mutable file variables and init-io!

bin/mirth0.c, src/mirth/data/error.mth, src/mirth/data/token.mth, src/mirth/elab.mth, src/mirth/eval.mth, src/mirth/lexer.mth
This mirrors the definition of `panic!` from `src/prelude/io.mth`.
```
def(emit-fatal-error!, *a Token Str -- *b +IO, ...)
```
I don't think the stack variable `*a` is necessary, but the compiler gave me an error `expected stack type in stack-type-concat` when I tried to remove it, so I left it there.
=> Make fatal errors stack-polymorphic

bin/mirth0.c, src/mirth/codegen.mth, src/mirth/data/arrow.mth, src/mirth/data/buffer.mth, src/mirth/eval.mth
This PR changes the codegen to use the elaborated arrows, instead of traversing the AST directly.
=> traverse arrows, not tokens during codegen

Makefile, bin/mirth0.c, build.bat, src/mirth.mth, src/mirth/codegen.mth, src/mirth/data/name.mth, src/mirth/elab.mth, src/prelude/common.mth
This PR defines two primitives, `argc` (an `Int`) and `argv` (a `Ptr`). These are implemented as global variables which are set to the value of the standard C `argc` and `argv` parameters to `main`, and are simply pushed to the stack when needed.
=> Support for command-line arguments

tools/mirth-atom/settings/language-mirth.cson
This enables `⌘-/` for toggling comments in atom.
=> define comment syntax for atom

bin/mirth0.c, src/mirth/data/token.mth, src/mirth/elab.mth, src/mirth/lexer.mth, src/prelude/test.mth
This PR defines the stack assertion construct. Inside a function, an assertion of the form `{A B C}` is equivalent to the identity function at the type `A B C -- A B C`.
I'm marking this as WIP since I'm not sure how to handle scoped type variables.
=> [WIP] Stack assertions

bin/mirth0.c, src/mirth/elab.mth, src/prelude/test.mth
Here I'm applying the suggestions from #83, namely
> > `+    elab-arrow-apply-sig-type!`
>
> Oh actually I just realised this probably doesn't work . . .
>
> Because IIRC elab-arrow-apply-sig-type! will freshen the morphism type before doing matching, so it's going to interact weirdly with type variables in the signature.
> 
> Probably we are better off doing some sort of manual matching here, not sure.
For this I moved the freshening logic from `elab-arrow-apply-sig-type!` so it's performed upfront, and split off a variant that doesn't do the freshening.
> > `+    elab-type-stack! drop nip`
>
> I think this is very close. One thing we probably want to check here is that the context you get back from elab-type-stack! is the same as the original context elab-ctx@. That way you can't …
=> Stack assertions cont

tools/mirth-vim/ftplugin/mirth.vim
This adds a vim plugin for mirth files. In particular, it defines a mirth-particular comment syntax.
This is useful for e.g. Nerdcommenter.
=> Add ftplgun with commentstring

bin/mirth0.c, src/mirth/codegen.mth, src/tests/pack-unpack.mth
Avoid allocating a cons cell when the `car` is nil and the `cdr` is primitive (i.e. not a cons cell).  (Yes ... these are backwards from lisp...)
=> Optimize pack1/unpack1 slightly

bin/mirth0.c, src/mirth/data/arrow.mth, src/mirth/data/ctx.mth, src/mirth/data/location.mth, src/mirth/data/name.mth, src/mirth/data/path.mth, src/mirth/data/string.mth, src/mirth/data/token.mth, src/mirth/data/var.mth, src/mirth/data/word.mth, src/mirth/elab.mth, src/tests/fancy-nominal.mth, src/tests/prim-types.mth
- Made `nominal(a, b)` and `def-type(a, b)` take an arbitrary type in `b`.
- Added `T.wrap` and `T.unwrap` words automatically when elaborating a nominal type `T`.
- Replaced many uses of `cast` with these `wrap` and `unwrap` words.
=> Improve nominal type support.

src/mirth.mth
Remove a vestigial comment about importing `snake` from when we couldn't specify the compile target on the command-line.
=> Remove comment about importing snake

bin/mirth0.c, src/mirth/codegen.mth, src/mirth/data/arrow.mth, src/mirth/data/buffer.mth, src/mirth/data/common.mth, src/mirth/data/ctx.mth, src/mirth/data/error.mth, src/mirth/data/location.mth, src/mirth/data/module.mth, src/mirth/data/name.mth, src/mirth/data/path.mth, src/mirth/data/prim.mth, src/mirth/data/subst.mth, src/mirth/data/token.mth, src/mirth/data/type.mth, src/mirth/elab.mth, src/mirth/elab/syntax.mth, src/mirth/lexer.mth, src/prelude/common.mth, src/prelude/test.mth, src/snake.mth
Part of this was adding support for multi-line words in the new syntax:
```
foo : Bar -- Baz
foo = (
something
something-more
)
```
=> Refactoring and rewriting a bunch in the new syntax.

src/tests/pattern-matching.mth
Adjust the pattern match test from #110 to also verify that pattern matching gives the constructor arguments back in the right order (i.e. the same order that was used to construct the value).
=> Test order on pattern match destructors

Makefile, install.sh
Adds a `make install` rule that installs a `mirth` executable at `~/.mirth/bin`
=> Add an install script

bin/mirth0.c, src/mirth/codegen.mth, src/mirth/data/arrow.mth, src/mirth/data/common.mth, src/mirth/data/prim.mth, src/mirth/data/token.mth, src/mirth/data/type.mth, src/mirth/elab.mth, src/mirth/lexer.mth, src/prelude.mth, src/tests/pattern-matching.mth, src/tests/test-blocks.mth, src/tests/test-prelude.mth
- Add block patterns in lambdas, which obsoletes `prim.run` (this closes #120 since we can just use a lambda instead, and may remove `prim.run` soon).
- Special support for "run vars" in the codegen and elaborator, which are important to make block patterns work.
- Currying: Type-permitting, `[x] foo` is now equivalent to `foo(x)`.
- Added curried implementations of `dip`, `if`, `while` primitives.
- Dropped `TParam` in favor of passing arrow types on the stack.
=> More higher-order word support.

bin/mirth0.c, src/mirth/codegen.mth, src/mirth/data/type.mth
This makes single-argument single-constructor data transparent, i.e. behave like newtypes in Haskell. For example, if you have the definition:
```Mirth
data Foo
FOO -> Int
end
```
Then, under the hood, `FOO` does nothing, and `match(FOO -> id)` does nothing.
=> Make single-argument single-constructor data transparent.

bin/mirth0.c, src/mirth/codegen.mth, src/mirth/data/common.mth, src/mirth/data/name.mth, src/mirth/data/prim.mth, src/prelude.mth
Introduce `prim.ptr.copy` (`memcpy`) and `prim.ptr.fill` (`memset`) primitives and speed up the compiler significantly (1.7s average run -> 1.1s average run, 1.5x speedup).
=> Speed up the compiler a bit.

bin/mirth0.c, src/data/char.mth, src/data/str.mth, src/mirth/codegen.mth, src/mirth/data/module.mth, src/mirth/data/name.mth, src/mirth/data/type.mth, src/mirth/input.mth
Adds some UTF8 support in data.char, data.str, mirth.codegen and mirth.data.input. This doesn't do any validation, just passes values along. Note that the representation of characters (`Char` type) is *encoded* UTF8 in a U32, in little endian order. This saves a lot of processing compared to working with codepoints directly.
=> UTF8 source support

bin/mirth0.c, src/data/lazy.mth, src/data/mut.mth, src/mirth/codegen.mth, src/mirth/data/prim.mth, src/mirth/data/type.mth, src/mirth/elab.mth, src/tests/test-mut.mth
Adds a `Mut` primitive type, which represents a (garbage-collected) mutable cell of a certain type. The main reason to do this is to implement explicit lazy evaluation (in a future PR), so we can improve the control flow in the compiler & enforce fewer restrictions on program order.
=> Add Mut primitive type.

Makefile, bin/mirth0.c, src/mirth/codegen.mth
Fixes the following error when building on macOS 14:
```
gcc -std=c99 -Wall -Wextra -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter -Wno-unused-value -Wno-missing-braces -Werror -pedantic -O0 -g -o bin/mirth0 bin/mirth0.c
bin/mirth0.c:452:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static void do_pack_uncons() {
^
void
bin/mirth0.c:640:21: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static void do_debug() {
^
void
2 errors generated.
make: *** [bin/mirth0] Error 1
```
=> c99: fix -Wstrict-prototypes error on clang 15

bin/mirth0.c, src/mirth/codegen.mth, src/mirth/data/arrow.mth, src/mirth/elab.mth
Makes generated names for blocks in the codegen depend on the owning word (the "home" of the arrow), instead of depending on the line number.
This should reduce merge conflicts somewhat for bin/mirth0.c somewhat, and improve diffs in general.
=> Make block names more stable in the codegen.

bin/mirth0.c, src/data/set.mth, src/mirth/codegen.mth, src/mirth/data/arrow.mth, src/mirth/data/external.mth, src/mirth/data/module.mth, src/mirth/data/name.mth, src/mirth/data/table.mth, src/mirth/data/type.mth, src/mirth/elab.mth, src/tests/error-recursive-block-type.mth
Unless I've missed some field, this PR concludes the work of changing table fields to use `Lazy` instead of representing that sort of mutable state across several fields. It also improves the representation of a few other fields.
=> Use Lazy in tables instead of mutable state when possible.

bin/mirth0.c, src/data/bag.mth, src/data/list.mth, src/data/map.mth, src/data/maybe.mth, src/data/set.mth, src/data/stack.mth, src/data/str.mth, src/mirth/codegen.mth, src/mirth/data/arrow.mth, src/mirth/data/ctx.mth, src/mirth/data/location.mth, src/mirth/data/name.mth, src/mirth/data/token.mth, src/mirth/data/type.mth, src/mirth/data/var.mth, src/mirth/elab.mth, src/prelude.mth
Adds syntactic sugar to perform pattern matching right from `def`:
```
def(name, type,
pattern1 -> casebody1,
pattern2 -> casebody2,
...
patternN -> casebodyN)
```
is now equivalent to,
```
def(name, type,
match(
pattern1 -> casebody1,
pattern2 -> casebody2,
...
patternN -> casebodyN
))
```
=> Add pattern matching syntax sugar to `def`

bin/mirth0.c, src/mirth/codegen.mth, src/mirth/data/arrow.mth, src/mirth/data/prim.mth, src/mirth/elab.mth, src/tests/test-blocks.mth, src/tests/test-prelude.mth
This PR fixes applicative syntax (finally!!), so that the order in which parameters are pushed on the stack matches the order of the parameters. Previously, `foo(bar,baz)` was equivalent to `[baz] [bar] foo`. Now it's equivalent to `[bar] [baz] foo`. This makes it a lot more sensible to use `if` and `while` curried, for example:
- `[then] [else] if` is equivalent to `if(then, else)`
- `[cond] [body] while` is equivalent to `while(cond, body)`
As part of this, we update the (recent) syntactic sugar related to parameter passing. In particular,
- `def(foo(f,g), type, body)` is now equivalent to `def(foo, type, \([f] [g] -> body))`
- likewise `def(foo(f,g), type, match-cases...)` is now equivalent to `def(foo, type, \([f] [g] -> match(match-cases...)))`
- for type signatures, `(sig1,sig2) dom …
=> Fix applicative parameter stack order.

bin/mirth0.c, src/mirth/data/prim.mth, src/mirth/elab.mth, src/mirth/mirth.h, src/prelude.mth
This way you can see the prim-type that is missing, instead of getting a stack trace that doesn't tell you what you really want.
=> Fix prim-type is set check.

bin/mirth0.c, src/mirth/data/name.mth, src/mirth/data/type.mth
AFAICT nil names are no longer used.
=> Remove name-is-nil

bin/mirth0.c, src/data/byte.mth, src/data/either.mth, src/data/list.mth, src/data/str.mth, src/mirth/codegen.mth, src/mirth/data/data.mth, src/mirth/data/def.mth, src/mirth/data/match.mth, src/mirth/data/name.mth, src/mirth/data/prim.mth, src/mirth/data/token.mth, src/mirth/data/type.mth, src/mirth/data/var.mth, src/mirth/elab.mth, src/mirth/mirth.h, src/platform/posix.mth, src/prelude.mth, src/scratch/resources.mth, src/tests/error-recursive-block-type.mth
This PR adds a resource stack alongside the usual value stack. Resources are linear, so they cannot be `dup`ed or `drop`ed. They can be used to represent mutable state in a program. They can also be used as capabilities for external interaction (e.g. file handles) requiring explicit creation, destruction, and sequencing of all the operations in between.
What is implemented in this PR:
1. TYPES: Resources are incorporated into `StackType` with the `STWith` constructor. This means that `StackType` represents both the value stack and the resource stack. There's special logic inside `StackType` unification so that the `STCons` and `STWith` stack type constructors commute against each other as needed, which makes resources and values act as independent stacks for the purposes of type checking. …
=> Add linear resource types to Mirth.

bin/mirth0.c, src/mirth/elab.mth, src/tests/resource-smuggling.mth
Fixes the issue of letting value types containing resources, which would let you duplicate and drop resources non-linearly. Adds a regression test.
=> Add a check to prevent resource smuggling.

bin/mirth0.c, src/mirth.mth, src/mirth/codegen/c99.mth, src/mirth/data/arrow.mth, src/mirth/elab.mth
The arrow builder words (`ab-...`) in `mirth.elab` were developed long ago with resources in mind. Now that resources are implemented, this PR updates these words to use a new resource, `+AB`, rather than stuffing that state in global variables.
[The old implementation via global variables was especially problematic because these arrow builder words need to be re-entrant, since you might need to build a new arrow while you're already building an arrow. So these words had some ad hoc logic to save and restore these global variables when needed. This is all gone now thankfully, since resources exist on a stack & don't interfere with each other, unlike global variables.]
=> +AB (arrow builder) resource.

bin/mirth0.c, src/mirth/codegen/c99.mth, src/mirth/data/external.mth, src/mirth/elab.mth, src/snake.mth
This PR adds a new form for def-external that lets you give the (external) symbol name separately from the (internal) word name:
```
def-external(name -> symbol, type)
```
The old form `def-external(name, type)` continues to work and is equivalent to `def-external(name -> name, type)`.
An example of the new form is in snake.mth where we have the declaration,
```
def-external(libc-rand -> rand, Int)
```
So that when we use `libc-rand` from mirth code, it invokes the external symbol `rand`.
=> Add ability to give def-external an external symbol different from the defined name.

bin/mirth0.c, src/mirth-tests/error-def-expects-three-arguments.mth, src/mirth-tests/error-def-missing-expects-three-arguments.mth, src/mirth/elab.mth, src/mirth/error.mth, src/mirth/word.mth
This PR removes the last vestiges of optional type signatures in `def` and `def-missing`. Optional type signature support has already been removed a while ago, this PR just makes the check more up front, by requiring three arguments in `def` and `def-missing`.
=> Require three arguments to def.

bin/mirth0.c, src/mirth-tests/error-alias-circular-1.mth, src/mirth-tests/error-alias-circular-2.mth, src/mirth-tests/error-alias-syntax-expected-argend.mth, src/mirth-tests/error-alias-syntax-expected-comma.mth, src/mirth-tests/error-alias-syntax-params-lhs.mth, src/mirth-tests/error-alias-syntax-params-rhs.mth, src/mirth-tests/error-alias-syntax-too-few-args.mth, src/mirth-tests/error-alias-syntax-too-many-args.mth, src/mirth-tests/error-alias-target-ambiguous.mth, src/mirth-tests/error-alias-target-not-visible.mth, src/mirth-tests/error-alias-target-undefined.mth, src/mirth-tests/error-alias-target-unknown.mth, src/mirth-tests/error-non-uniform-match.mth, src/mirth/alias.mth, src/mirth/def.mth, src/mirth/elab.mth, src/std/prelude.mth
- Defer alias target resolution until necessary.
- Use proper name resolution for alias target.
- Add lots of syntax checks for the `alias` declaration.
- Prevent circular aliases, e.g. `alias(foo, foo)` or `alias(x, y) alias(y, x)`
- Add tests for all of these.
- Also use an alias for Bool.if instead of a def-missing.
=> Improve alias errors and tests.

bin/mirth0.c, src/mirth-tests/data-labels.mth, src/mirth/c99.mth, src/mirth/data.mth, src/mirth/elab.mth, src/mirth/mirth.h
This PR adds runtime support for data labels. This means we can now define a `data` type that uses labels, e.g.
```mirth
data(Person, PERSON -> age:Int name:Str)
```
Then the `PERSON` constructor will have type `[ age:Int name:Str -- Person ]`. When pattern matching you get the labels back, so we can define projection functions like so,
```mirth
def(Person.age, Person -- Int, PERSON -> name> drop age>)
def(Person.name, Person -- Str, PERSON -> age> drop name>)
```
In a future PR I'd like to generate these projection functions automatically.
=> Add runtime support for data labels and a test.

bin/mirth0.c, src/args/state.mth, src/args/types.mth, src/mirth-tests/data-labels.mth, src/mirth/c99.mth, src/mirth/data.mth, src/mirth/elab.mth, src/mirth/match.mth, src/mirth/mirth.h
This PR changes `data` to make it generate a few functions in the case where the `data` type has a single constructor. Suppose we have a data type called `Foo` and it has a single constructor `FOO`. Then the compiler will generate:
- a method `Foo./FOO` that undoes the action of the constructor. It is defined as `match(FOO -> )`
- for each labelled input to the `FOO` constructor, for example `bar:Bar`, it generates a method `Foo.bar` of type `Foo -- Bar`  that fetches that field. This is defined as `/FOO bar> dup >bar dip(FOO drop)`
For the latter, if the data is actually a resource, it doesn't do the `drop`, so the method `+Foo.bar` will have type `+Foo -- +Foo Bar` and is defined as `/FOO bar> dup >bar dip(FOO)`.
=> Generate unpacking and label projection functions for single-constructor data types automatically.

bin/mirth0.c, src/args/parse.mth, src/args/state.mth, src/args/types.mth, src/mirth-tests/data-labels.mth, src/mirth/elab.mth
This PR generates a function that modifies labelled data fields, for single constructor functions.
E.g. `data(Foo, FOO -> bar:Bar)` now  also generates a method `Foo.bar!` with type `Bar Foo -- Foo`.
=> Create `label!` words automatically for single-constructor words.

Makefile, bin/mirth0.c, run.sh, src/mirth-tests/lens-syntax.mth, src/mirth/data.mth, src/mirth/elab.mth, src/mirth/lexer.mth, src/mirth/name.mth, src/mirth/token.mth, src/std/byte.mth, src/std/maybe.mth, src/std/stack.mth
This PR implements reserves colon (`:`) as a special token, and turns it into a right-associative application operator, as an alternative for parentheses in many situations.
This new syntax can be used in place of unary application, whenever the argument consists of a single atom (including the atom's arguments). For example `foo(bar)` can be replaced with `foo:bar`. The syntax is right-associative, so `foo(bar(baz))` can be replaced with `foo:bar:baz`.
The primary motivation for this syntax is to be able to compose multiple higher-order words without creating a mess of parentheses. In particular, this syntax should be useful for defining and using functions to access deeply nested fields. Hence calling it "lens syntax".
Examples of the syntax:
- `foo:bar` is equivalent to `foo(bar)`
- …
=> Make colon a right-associative application operator -- lens syntax.

bin/mirth0.c, src/mirth-tests/error-alias-syntax-params-lhs.mth, src/mirth-tests/error-alias-target-not-visible.mth, src/mirth-tests/lens-syntax.mth, src/mirth-tests/multiple-arities.mth, src/mirth-tests/test-blocks.mth, src/mirth-tests/test-prelude.mth, src/mirth/c99.mth, src/mirth/data.mth, src/mirth/elab.mth, src/mirth/main.mth, src/mirth/module.mth, src/mirth/name.mth, src/mirth/package.mth, src/mirth/prim.mth, src/mirth/type.mth, src/mirth/word.mth, src/posix/posix.mth, src/std/lazy.mth, src/std/prelude.mth
This PR makes word arity part of the internal qualified name of the word. As a result, we can have multiple words with the same name, as long as they have different arities.
Consequences:
- Currying is no longer automatic.
- When setting an `alias` for a higher-order word, you have to indicate the number of parameters as part of the alias definition. This is done by supplying a parameter list. Other than the arity, the argument list is ignored.
[Also incidentally I added `+World.put` and `+World.line`]
=> Allow for multiple words with the same name & different arities.

bin/mirth0.c, src/args/state.mth, src/mirth-tests/lens-syntax.mth, src/mirth/elab.mth
This PR adds implements lens-like functions for labelled inputs to single-constructor data types. E.g. given the following data definition,
```mirth
data(Person, PERSON -> name:Str age:Int)
```
Then previously the compiler would generate the following words:
```
/PERSON :: Person -- name:Str age:Int
Person.name :: Person -- Str
Person.name! :: Str Person -- Person
Person.age :: Person -- Int
Person.age! :: Int Person -- Person
```
With the changes in this PR, the compiler will generate two additional words:
```
Person.name(f) :: (*a Str -- *b Str) *a Person -- *b Person
Person.age(f) :: (*a Int -- *b Int) *a Person -- *b Person
```
Note that these new functions have the same name as the field projection functions (`Person.name` and `Person.age`) but they have a different arity. With these …
=> Generate lens functions automatically.

Makefile, bin/mirth0.c, src/mirth/arrow.mth, src/mirth/c99.mth, src/mirth/data.mth, src/mirth/elab.mth, src/mirth/mirth.h, src/mirth/need.mth
This PR replaces linked lists in the runtime with flat tuples, and uses them to improve the representation of data. It also makes data field accessing a runtime primitive.
Compile time comparisons on my dev machine:
- `make` went from 48s down to 40s
- `make bin/mirth1.c` went from 9.5s down to 5.5s
=> runtime: Use flat tuples rather than linked lists.

Makefile
=> Pass -g flag only on debug targets.

Makefile, bin/mirth0.c, src/mirth-tests/error-name-resolution-constructors.mth, src/mirth-tests/error-name-resolution-types.mth, src/mirth-tests/test-blocks.mth, src/mirth/elab.mth, src/mirth/main.mth, src/std/list.mth
This PR brings good name resolution to constructors in `match` statements. You can now have constructors of the same name without fear, because `match` will prefer the constructor in the type's namespace. If there is still ambiguity (e.g. if there's both a value type and a resource type with the same constructor name available to match at the same time -- see the example in the test) you can use a qualified name to resolve it.
Closes #227
=> Implement name resolution for constructors in pattern matching.

bin/mirth0.c, debug.sh, src/mirth-tests/warning-recursive-inline.mth, src/mirth/elab.mth, src/std/lazy.mth
Adds a check that a word marked as inline cannot be directly recursive (or indirectly recursive through other inline words). If it is found to be recursive, a warning is issued and the word is marked as not inline.
Fixes #249 (importing std.prelude as inline will just generate a bunch of warnings now).
=> Add a check for inline recursion.

bin/mirth0.c, src/mirth-tests/error-name-resolution-words.mth, src/mirth/elab.mth, src/mirth/type.mth
This PR changes the name resolution during word elaboration to:
- explain why each candidate was rejected
- continue type checking with partial type information
Also this enables more flexible qualified names, e.g. you can refer to a word `foo` defined in `std.prelude` simply by `prelude.foo`, no need to specify the package name (unless there's two `prelude` modules imported, and they both define a `foo` word ... in which case you do need to specify the package also).
This fixes #223 and #222.
=> Better name resolution during word elaboration.

bin/mirth0.c, src/mirth-tests/labels.mth, src/mirth/elab.mth, src/mirth/lexer.mth, src/mirth/token.mth
This tiny PR adds two new forms of syntax sugar, relating to stack labels:
- `^foo` will dup the top value for stack label `foo`, and push it on the stack.
- `^foo:f`, or equivalently `^foo(f)`, will pop the `foo` label, run `f`, then push the `foo` label again.
In other words:
- `^foo` is equivalent to `foo> dup >foo`
- `^foo:f` is equivalent to `foo> f >foo`
The rationale behind these is that they're both very useful, in particular `^foo` to access the label value, is otherwise very cumbersome to write. These will make it very easy to replace local variables in most cases.
Also a useful thing to do with these is to `dip` a stack label, because `^foo:dip(f)` is equivalent to `foo> dip(f) >foo`.
=> Add "label lens" syntactic sugar, for easy access to top label value.

Makefile, bin/mirth0.c, src/examples/sdl2.mth, src/examples/snake.mth, src/snake/main.mth, src/snake/sdl2.mth, src/std/list.mth
This PR tries to make the SDL2 bindings a little more modern by using resources. The snake example was mostly rewritten using the modern API.
Not everything has been converted to mirth-friendly types -- the renderer and event polling APIs are still very raw.
=> Try to make snake more solid.

.github/workflows/build.yml
The change to macos-latest moved macos-14 which runs on arm64. This PR adds macos-12 runner so we don't stop testing on x64-based macs.
=> Add macos-12 runner for CI.

src/main.mth
With the new name resolution the qualification is no longer needed on the argument parser constructors.
=> Remove qualification for argparser types

bin/mirth0.c, src/arrow.mth, src/data.mth, src/elab.mth, src/prim.mth, src/specializer.mth, src/table.mth, src/type.mth
In #271 I accidentally renamed some words that are used to create stack types. This PR reverts that accidental change.
=> Fix T*, T+, T-> names.

bin/mirth0.c, debug.sh, src/data.mth, src/lexer.mth, src/name.mth, test/data-labels.mth, test/labels.mth
Changes the syntax of resource labels slightly (see #276):
- Resource labels must begin with a `+`, e.g. `+foo: +MyResource` as part of a type signature, says that the resource `+MyResource` is pushed on the `+foo` resource label.
- Because resource labels start with`+`, and value labels do not, they can be immediately distinguished.
Thus the push and pop syntax for resource labels has been simplified to be more similar to value labels:
- `>+foo` pushes a resource onto `+foo`
- `+foo>` pops a resource from `+foo`
Because the names are disjoint, no ambiguity arises about whether we're pushing/popping from the resource stack or the value stack.
- Of the three label access functions defined in #276 (see last part), only `@+foo(f)` is defined for resource labels.
=> Make resource labels use + as a prefix.

bin/mirth0.c, src/elab.mth, src/label.mth, test/error-label-type-resource-mismatch.mth
Requires that only resources be used in resource labels, only value types be used in value labels. Adds a test.
=> Add checks that types aren't used as resources and vice versa via labels.

Makefile, bin/mirth0.c, build.bat, lib/std/list.mth, lib/std/maybe.mth, lib/std/path.mth, lib/std/posix.mth, lib/std/str.mth, magic/magic.c, mirth-test.sh, src/c99.mth, src/elab.mth, src/main.mth, src/name.mth, src/package.mth, test/error-module-name-mismatch.mth, test/test-is-directory.mth
This PR implements two main changes:
- When loading a module via a module path without knowing a package path (e.g. because the module path is passed in as the command-line argument to the mirth compiler), then infer the package path from the module path. e.g. if loading module `foo.bar`, from `my/directory/bar.mth`, it will infer that package `foo`'s path is `my/directory`.
- When loading a module via its name, and you don't know where the package is, it will look for a package in a predefined list of directories -- the "package search path". Right now, the search path is hardcoded to be just the "lib" directory, but it should be easy to make package search path configurable in the future (e.g. adding a `-P` option).
Together these eliminate all the necessary uses of `-p` package flags …
=> Package resolution: Derive package path from module path, and have a default package search path.

.vscode/tasks.json, Makefile, test/external-fnptr.mth, tools/build.bat, tools/build.sh, tools/build32.bat, tools/build64.bat, tools/mirth-test.sh
Also adds a test for fnptrs in def-external.
Also adds a few options to mirth-test.sh:
- `-p` option to print the golden test comments
- you can run a single test by passing a file path, e.g. `tools/mirth-test.sh -p test/hello-world.mth`
=> More build.sh stuff

bin/mirth0.c, examples/sdl2.mth, examples/snake.mth, lib/std/ctypes.mth, lib/std/posix.mth, src/c99.mth, src/elab.mth, src/external.mth, src/mirth.mth, src/prim.mth, test/external-block.mth, test/external-deprecated-def.mth, test/external-fnptr.mth, test/external-labelled-argument.mth
This PR expands and replaces `def-external` with `external`. The new `external` declaration can be used the same way as `def-external`, but it also allows you to make C declarations directly. E.g.,
```
external(
"#include <stdio.h>"
"void printint(int x) { printf(\"%d\", x); }"
printint [ +World CInt -- +World ]
)
```
This example has both raw C declarations (the string literals), and an external function declaration `printint [ +World CInt -- +World ]`.
Note the new syntax for declaring an external function, where the type signature is passed in the brackets:
```
name [ type-sig ]
name -> symbol [ type-sig ]
```
The old syntax (passing the type signature as a separate argument) is still supported, but not recommended.
=> Flexible external declaration.

bin/mirth0.c, src/c99.mth, src/elab.mth, test/external-labelled-output-missing.mth, test/external-labelled-output.mth, test/external-too-many-outputs.mth
This PR changes `external` slightly so that any labelled outputs get treated as "inout" arguments. They are pushed back on the stack after the `external` call. This makes it possible to call functions that follow the extremely common pattern (in C, C++, Rust) of data that is passed by reference and modified in place.
E.g.
```
data( +Res, +Res -> CPtr(CInt) )
external(
foo [ +x:+Res -- +x:+Res CInt ]
"int foo(int* x) { return *x++; }" 
)
```
Note how `foo` is declared to have two outputs -- a labelled resource output `+x:+Res` and an unlabelled value output `CInt` -- but the corresponding C function only has the `int` output. That's because the labelled resource output `+x` is taken from the inputs and pushed back on the stack.
If an output label is not present in the input, the compiler …
=> Allow inout arguments in externals via labels.

bin/mirth0.c, src/elab.mth, test/error-name-resolution-constructors.mth, test/error-name-resolution-types.mth, test/error-name-resolution-words.mth, test/labels.mth
This PR is a bit of an experiment to relax visibility checks somewhat.
Previously, if you tried to use a definition made in some module, you needed to have imported that module directly.
With this PR, we change name resolution so that:
- if it's a relative name, e.g. invoking a method on a type, or a constructor during pattern matching, then no direct visibility is required.
- if it's an absolute name, e.g. a type name like `List`, or a global defined in some module like `swap`, then the defining module must be imported.
- if it's a qualified name, then the root of the qualified name must be directly visible (e.g. if the root is a module, it must be directly imported; if the root is a type, its defining module must be directly imported).
Of note, these checks were all in place already. …
=> Relax visibility checks.

bin/mirth0.c, src/arrow.mth, src/elab.mth, src/tycon.mth, src/type.mth, src/word.mth, test/def-syntax.mth, test/error-def-expects-three-arguments.mth, test/type-inference.mth
This PR adds a new `def` syntax:
```
def word [ type-sig ] { body }
```
which is sugar for `def(word, type-sig, body)`.
In addition, the `[type-sig]` is optional, in which case a bit of type inference is implemented.
Because mirth is contextual, the type inference makes a few useful assumptions based on the name:
- if you're writing a type-qualified word that looks like a method, e.g. `List.my-method`, then it assumes that qualifying type is the top input: `*? List(?) -- *?`
- if you're writing a type-qualified word that looks like a constructor, e.g. `List.SuperCons`, then it assumes that qualifying type is the top output, `*? -- *? List(?)`. (By the way, "looks like a constructor" means it's a qualified word that starts with an uppercase letter. "Looks like a method" is everything …
=> New def syntax and type inference.

bin/mirth0.c, src/elab.mth, test/match-syntax.mth, test/stack-assertions.mth, test/test-prelude.mth
This PR adds syntactic sugar to match. In particular:
- you can use curly braces around the cases, instead of round ones, so `match { ... }` is equivalent to `match ( ... )`
- instead of writing the match cases as comma-separated arguments, you can write each case enclosed in curly braces. e.g. `match( { A -> B } { C -> D } )` is the same as `match( A -> B, C -> D )`.
So the following are equivalent:
```
match ( A -> B, C -> D )
match { A -> B, C -> D }
match ( { A -> B } { C -> D } )
match { { A -> B } { C -> D } }
```
In addition the new cases syntax carries over to definitions, so for example you can write,
```
def foo {
{ A -> B }
{ C -> D }
}
```
=> add syntactic sugar for match and match cases

bin/mirth0.c, src/data.mth, src/elab.mth, test/data-get-tag.mth, test/error-data-tag-overlap.mth
This PR adds a way to specify a tag value for `data` types. This closes #233.
To use it, place an integer value *before* the tag name, e.g.:
```
data(MyData, 10 Foo, 20 Bar, 30 Baz)
```
This causes the `.tag` value for `Foo` to be 10, `Bar` to be 20, and `Baz` to be 30.
If you omit a number, it will use the number than the previous tag's number. So for example, the following are equivalent:
```
data(MyData, 10 Foo, 11 Bar, 12 Baz)
data(MyData, 10 Foo, Bar, Baz)
```
If two tag values are the same, the compiler raises an error. (Use an alias instead.)
=> Add way to specify tag value.

bin/mirth0.c, src/elab.mth, src/name.mth, src/prim.mth, src/token.mth, test/data-syntax.mth
This PR adds syntactic sugar for `data` declarations. Now we can write them as follows:
```
data Maybe(t) {
None
Some [ t ]
}
```
Constructors can still be written in the old style, with arrows and commas:
```
data Maybe(t) {
None,
Some -> t,
}
```
In addition, I added a `struct` declaration, which is syntactic sugar for a single-constructor `data` declaration:
```
struct Person {
name: Str
age: Int
}
```
is equivalent to:
```
data Person {
Person [
name: Str
age: Int
]
}
```
The rationale behind the new data syntax is to make it look visually distinct from the new `def` syntax, so that it's easier to not confuse them, which was a problem with the old style.
=> Add new syntax for data, & add struct declarations.

bin/mirth0.c, src/elab.mth, src/main.mth, src/mirth.mth, src/name.mth, src/package.mth
Replaces the existing PACKAGE_SEARCH_PATH variable with a field in the +Mirth resource and adds the `-P` command line flag to add items to it, without any package search path flags it defaults to `lib`. This also replaces the couple `data` definitions related to +Mirth with the struct syntax sugar, but that's easy to undo separately from the rest of the changes if not wanted.
=> Make package search paths part of the +Mirth resource and add a CLI argument to add to it

bin/mirth0.c, examples/snake.mth, lib/std/list.mth, lib/std/map.mth, lib/std/maybe.mth, lib/std/prelude.mth, lib/std/test.mth, src/arrow.mth, src/c99.mth, src/def.mth, src/elab.mth, src/match.mth, src/module.mth, src/name.mth, src/specializer.mth, src/type.mth, src/var.mth, src/word.mth, test/default-word-param.mth, test/match-syntax.mth
This PR adds the ability to define a default for parameters to higher-order words. The default is evaluated in the caller's environment, so this can be used to pass a type-aware equality, and things like that, automatically.
Example:
```
def foo (f { bar } ) { f f }
def bar { ... }
```
Here, if we call `foo` with no arguments, this is the same as calling `foo(bar)`.
More useful example, defining a higher-order equality word on generic types:
```
def Maybe.== (eq {==})  {
{ None -> none? }
{ Some -> swap match {
{ None -> drop False }
{ Some -> swap eq }
}
}
```
Now when we call `==` on a Maybe value, the mirth compiler fills in the default argument so it is equivalent to writing `==(==)`. Therefore we can call `==` on Maybe to test equality for a bunch of different types, without having …
=> Add default parameters for higher-order words.

bin/mirth0.c, lib/std/prelude.mth, lib/std/str.mth, src/c99.mth, src/lexer.mth, src/mirth.h, src/prim.mth, test/str-to-x.mth
This PR adds prim-str-to-f32 and prim-str-to-f64 primitives, which are wrappers around strtof and strtod respectively.
It exposes these in `std.str` as `Str.parse-f32` and `Str.parse-f64` for prefix parsing, and as `Str.>F32?` and `Str.>F64?` for full string parsing.
=> String to float parsing primitives.

bin/mirth0.c, src/mirth.h, test/unpack-then.mth
value_bool is used in the codegen but it was missing in mirth.h, this PR adds it, and a test that triggers value_bool in the codegen.
=> Add missing value_bool definition.

bin/mirth0.c, src/mirth.h, test/negate.mth
The bounds check on integer multiplication had the potential to trigger INT64_MIN/-1, and unfortunately this would always happen when calling Int.negate with a positive number.
=> Fix Int.negate and integer multiplication bounds check

bin/mirth0.c, examples/fractal.mth, examples/sdl2.mth, lib/std/file.mth, lib/std/list.mth, lib/std/map.mth, lib/std/maybe.mth, lib/std/prelude.mth, src/c99.mth, src/data.mth, src/def.mth, src/elab.mth, src/lexer.mth, src/main.mth, src/match.mth, src/mirth.mth, src/name.mth, src/specializer.mth, src/token.mth, src/type.mth, src/var.mth, test/chaining-colons.mth, test/error-alias-target-not-imported.mth, test/labels.mth, test/std-list.mth, test/type-inference.mth
This started as a lexer bugfix (chained label tokens were broken) that turned into a refactoring, that resulted in some changes to Maybe words and a new label helper function . . .
- Refactored the lexer to use the new `data` syntax for the most part.
- Fixed a bug that meant label helper functions like `@foo/1` were not chaining correctly with colon. With this fix we can now write `@x:@y:swap` for example, to the top of the `x` and `y` labels.
- Renamed `Maybe.if-some` and `Maybe.or-some` to `Maybe.if?` and `Maybe.or?` respectively. Added `Maybe.then?`, `Maybe.else?`, and `Maybe.and?` functions as well, which are "Maybe" counterparts to the respective boolean-flavored words.
- Added a new label helper syntax, `!foo(f)` which is short for `>foo f foo>`. This is dual to the `@` helper, …
=> Refactor Lexer, fix chained label token lexer bug, add !foo/1 label helper, rename some Maybe words.

lib/std/prelude.mth
I almost forgot about this. Enabled the primitives. Mirth can now read and write floating point values from pointers and buffers.
=> Enable floating point primitives

lib/std/buffer.mth
Sorry, for all the PRs, I forgot to enable these primitives in the `+Buffer` resource. This should be the last commit related to this.
=> Enable floats for buffers

bin/mirth0.c, src/elab.mth, src/macro.mth, src/version.mth, test/conditional-compilation.mth
This PR introduces `mirth-revision`, a (manually updated) integer that can be used for conditional compilation across versions of the compiler via `min-mirth-revision` and `max-mirth-revision` declarations.
The current revision is  `20250126001`. When we add some new language feature we can update this number, let's say we updated it to `20250126002`, then we can use:
```
min-mirth-revision 20250126002 { ... }
```
to start using the new feature right away inside this block. We can also use `max-mirth-revision` to target the previous versions:
```
max-mirth-revision 20250126001 { ... }
```
This should make it easier to support multiple versions of the compiler with the same code, which is useful for bootstrapping (& in general for libraries).
=> Introduce conditional compilation via max-mirth-revision and min-mirth-revision.

bin/mirth0.c, lib/std/either.mth, lib/std/maybe.mth, lib/std/prelude.mth
Includes:
- `Maybe` and `Either` methods for doing more monadic flow control, including a `switch(case(predicate, f), default)` pattern for both.
- `until/1` and `until/2` for the inverse of `while` (it just reads better sometimes).
- `if/3` so you can factor out a `dup` that comes in front of an `if/2` (I find this is a really common pattern and it reads clearer to just include the predicate as part of the `if`)
- A few other random things
=> Add more std lib functions

bin/mirth0.c, src/lexer.mth
The language server is going to need to be able to lex code that is stored in memory and not in a file (since you can do syntax highlighting, etc on unsaved files). Given that in most cases it's better performance to load a string into memory than to operate in a streaming fashion, it seems like this switchover is overall an improvement.
It was nice how easy this was to do. The consuming code doesn't need to aware of the change at all!
=> Use strings instead of input for lexer

bin/mirth0.c, src/mirth.mth, src/name.mth
No idea if this is desirable at this point or not so feel free to ignore, but I had the idle thought while poking at this code that this could be using a `+Buffer` stored in `+Mirth` instead of a global buffer and I wanted a chance to learn how `+Buffer` works.
=> Replace name hash buffer with `+Buffer`

.gitattribute, .gitattributes, .gitconfig
When a conflict occurs, this merge driver keeps local changes.
=> Add a custom merge driver for bin/mirth0.c

bin/mirth0.c, lib/std/list.mth, src/elab.mth, src/token.mth, src/type.mth, src/version.mth, test/ldip.mth, test/vdash.mth
This PR adds syntactic sugar for type signatures, the "vdash" `|-` syntax. It lets us factor out any type, resource, label, or stack base that appears both as an input and output. The basic idea is that instead of writing a type signature like this:
```
[ A B -- A C ]
```
We can write it like this instead:
```
[ A |- B -- C ]
```
Here `A` is considered a "context" for turning `B` into `C`. The context `A` is both passed as input and returned as output. This is purely a syntactic  convenience, so it's not like the context is treated any differently from other inputs or outputs, but it can be useful both in reducing the amount of repetition, and for documenting the intention of treating some input/output like a context.
The justificiation for adding this syntax is that we are quite often …
=> Add vdash syntactic sugar.

bin/mirth0.c, lib/std/file.mth, src/alias.mth, src/arrow.mth, src/buffer.mth, src/c99.mth, src/data.mth, src/def.mth, src/elab.mth, src/label.mth, src/lexer.mth, src/location.mth, src/macro.mth, src/main.mth, src/token.mth
Rewrites several type signatures using vdash syntax, roughly half of the modules in the mirth compiler.
This PR also includes the changes in #379.
=> Rewrite many type signatures using new syntax.

bin/mirth0.c, lib/std/file.mth, lib/std/str.mth, src/c99.mth, src/elab.mth, src/lexer.mth, src/type.mth, src/version.mth, test/resource-sliding.mth
This PR implements an automation for working with multiple resources: Whenever a specific sequence of concrete resource types is required, the elaborator will emit the necessary resource stack permutation to place them in the required order. In other words, it will slide resources past each other automatically. The elaborator only does this with concrete resource types, not with generic or unknown resources, so it only emits a resource stack permutation in cases that would have previously been considered a type error.
The main effect of this change has is that we no longer need to use  `rswap` and `rdip` manually when working with multiple resources, the compiler does it for us.
To take full advantage of this automation, name dispatching was changed so that it will dispatch on any of the …
=> Implement automatic resource sliding.

bin/mirth0.c, lib/std/file.mth, lib/std/posix.mth, src/elab.mth, src/specializer.mth, src/version.mth, test/resource-sliding.mth
The predicate for activating resource sliding had a bug which made it fail in cases where the resource stack has more resources than required. This PR fixes it.
Also this changes how args are handled in +AB, to make passing them explicit. This should make resource sliding work with higher-order words.
=> Fix resource sliding

bin/mirth0.c, src/elab.mth, src/lexer.mth, src/token.mth, test/label-lam.mth
Implements an experimental "label lambda" syntax. 
`\x` pushes to label `x`, and then pops `x` and drops it at the end of the current expression. So,
```\x ...```
Is the same as,
```>x ... x> drop```
This is a common enough usage pattern for labels that it's worth looking at ways to make it nicer.
=> Implement label lambda \x syntax.

bin/mirth0.c, lib/std/list.mth, lib/std/map.mth, lib/std/number.mth, src/data.mth, src/elab.mth, src/type.mth, test/auto-codip.mth
This PR introduces an automation intended to make writing higher-order words easier: whenever we apply an operation that has a fixed stack type base, such as against a stack type variable, the elaborator will now "co-dip" any extra stack items from the bottom of the stack, perform the operation, and then put those items back at the bottom. This automation only activates in situations that would previously have been type errors.
Before this PR, when writing higher-order words, we would have to be very careful about what went on the stack. E.g. if we want to implement a higher-order function that applies a unary function `f` to two elements, while maintaining access to the overall stack context, we would had to write something like this:
```
def on2(f) [ (*a b -- *a c) *a b b -- *a c c ] { …
```
=> Automatically co-dip extraneous values, resources, and labels when applying an operation against a fixed stack base.

bin/mirth0.c, src/elab.mth, src/macro.mth, test/ldrop.mth
`ldrop` is a macro which drops from all labels or from a list of labels: 
```
ldrop
ldrop(label1 label2 ... labeln)
```
In the first form, `ldrop`, it drops once from each visible label.
In the second form, `ldrop(label1 ... labeln)` drops from each label in the list. 
For resource labels, it tries to invoke the `rdrop` method on the corresponding type. It doesn't know how to handle second-order `rdrop` like `+Maybe.rdrop/1` and `+List.rdrop/1`. Hopefully in the future we will have better ways of doing generic methods, so these will eventually work.
=> Implements the ldrop macro.

bin/mirth0.c, lib/std/array.mth, src/main.mth, src/mirth.h, test/arrays.mth
The stride field wasn't being updated properly after pushing to an empty array, which led to segfaults. This PR fixes that.
=> Fix a bug with building arrays from nothing.

bin/mirth0.c, lib/std/array.mth, lib/std/buffer.mth, src/c99.mth, src/mirth.h, src/prim.mth, src/version.mth, test/arrays.mth
Go back to not having a fill value for arrays.
This means out of bound array access results in panic once again. You can recreate the old functionality by checking the length yourself and/or calling `Array.expand` / `+Array.expand!` manually beforehand.
The problem of not knowing how to allocate an array without having a value ahead of time was solved by not allocating anything for an empty array, I.e. use a null pointer internally to represent an empty array. This PR makes it a panic if you attempt to access an empty array's base pointer. But since you wouldn't be able to do anything safely with a pointer to an empty array, this is fine actually.
=> Drop Array fill value.

lib/std/byte.mth, lib/std/either.mth, src/c99.mth, src/data.mth, src/mirth.h, src/token.mth, test/struct-physical.mth
Only structs for now. And they are still heap allocated & reference counted even in cases where they need not be. Sum types still have the generic tagged tuple representation for now.
=> Represent mirth structs as C structs.

src/c99.mth, src/data.mth, src/match.mth
This PR changes the requirement for transparent types. A transparent type is a thin wrapper type, a `data` type with a single constructor and a single input, or equivalently, a `struct` with a single field. In this PR the requirement is strengthened so that the input must have a concrete type.
This precludes a type like this from being transparent: 
```
struct Wrapper(a) { a }
```
where the input is a type variable. Instead this will be treated as a struct type.
The reason to strengthen the requirement is so that transparent types can have their own type tag, so we can associate dynamic behavior with transparent types. If a single input type with a type variable were transparent, we would have to store the type variable's type tag somewhere, as well as the transparent type's tag whenever …
=> Change requirements for transparent types.

src/c99.mth
Change the representation of sum types, giving them each a bespoke C type (as a tagged union) and type tag. This is a follow up to representing mirth structs as C structs, and mirth enums as C enums.
=> Represent sum types as tagged unions.

src/c99.mth
Resources are owned, so they don't need reference counts.
=> remove reference counts from resource structs & unions

src/c99.mth, src/mirth.h, src/table.mth, src/type.mth
This finishes the work of assigning a tag to each type constructor, including primtiive types, table types, and all kinds of data types. This is done so we can add some dynamic behavior later.
=> Give every type constructor a unique runtime tag.
