mirth-lang/mirth

.github/workflows/selfbuild.yml
.github/workflows/tests.yml

Instead of running twice on pull request.

Run CI on push.

---

src/mirth/build.mth
src/mirth/elab.mth

Hooking up build (including self-build) to the elaborator.

Hook up elaborator to build

---

bootstrap/fail_types/fake_fail.mth
bootstrap/mirth.py
bootstrap/test.py

Report line numbers in the right place for vim integration.

Improve error reporting in bootstrap.

---

src/base/set.mth
src/mirth/core.mth

Non-hole unification to be implemented.

Implement unification for holes.

---

bootstrap/mirth.py
bootstrap/pass/trust_me.mth

This primitive works as a higher-order coerce.

Add a trust_me primitive and test in bootstrap.

---

mirth.mth
mirth0.c

The new while loop has signature
```
while(f : *a Bool -- *a, g : *a -- *a) : *a -- *a
```
and resembles the C-family `while` a lot more.

Make a better while loop.

---

bin/mirth0.c
src/mirth/codegen.mth
src/mirth/data/ctx.mth
src/mirth/data/external.mth
src/mirth/data/name.mth
src/mirth/data/subst.mth
src/mirth/data/token.mth
src/mirth/data/type.mth
src/mirth/data/var.mth
src/mirth/elab.mth
src/mirth/eval.mth
src/mirth/input.mth
src/mirth/lexer.mth
src/prelude/common.mth
src/prelude/heap.mth
src/prelude/str.mth
src/prelude/test.mth
src/snake.mth

* Uses <stdbool.h>
* Also adds the following words: true, false, &&, ||, nonzero

Add native Bool type

---

Makefile
README.md
tools/mirth-atom/CHANGELOG.md
tools/mirth-atom/README.md
tools/mirth-atom/grammars/mirth.json
tools/mirth-atom/package.json
tools/mirth-code/syntaxes/mirth.tmLanguage.json

* Uses the same grammar as VSCode

Add Mirth package for Atom

---

bin/mirth0.c
src/mirth.mth
src/mirth/codegen.mth
src/mirth/data/name.mth
src/mirth/data/prim.mth
src/mirth/data/type.mth
src/mirth/elab.mth
src/prelude/test.mth

Adds types for monomorphic primitives, and uses them in the elaborator.

Types for monomorphic prims

---

.github/workflows/build.yml
Makefile
bin/mirth0.c
src/mirth/elab.mth
src/mirth/lexer.mth
src/prelude/common.mth

This fixes #87 and adds a regression test via CI.

Reinstate def-external.

---

mirth-test.sh
src/tests/badtype.mth
src/tests/badtypewithtarget.mth
src/tests/empty.mth
src/tests/identity.mth

This is the beginnings of a really rudimentary golden testing harness for Mirth. Not hooked up to CI yet.

Rudimentary golden testing.

---

bin/mirth0.c
src/mirth/elab.mth
src/prelude/common.mth

Use a nominal type over a tuple to clean up the type elaborator a little bit!

Clean up type elaboration.

---

bin/mirth0.c
src/mirth/data/name.mth
src/mirth/data/token.mth
src/mirth/lexer.mth
src/prelude/common.mth
src/prelude/heap.mth

Mostly this was about reviewing everything that's in the prelude. 😅

Rewriting prelude in new syntax.

---

Makefile

Squash "suggest braces around initialization of subobject" errors

---

bin/mirth0.c
src/mirth/data/data.mth
src/mirth/data/type.mth
src/mirth/elab.mth
src/tests/error-missing-patterns.mth
src/tests/error-overlapping-pattern.mth

Adds pattern match exhaustiveness checks, and more tests for pattern matching.

Pattern match exhaustiveness check

---

bin/mirth0.c
src/mirth/codegen.mth
src/mirth/data/buffer.mth
src/mirth/data/common.mth
src/mirth/data/data.mth
src/mirth/data/external.mth
src/mirth/data/module.mth
src/mirth/data/name.mth
src/mirth/data/prim.mth
src/mirth/data/type.mth
src/mirth/data/word.mth
src/prelude/common.mth
src/tests/error-word-already-defined.mth

- Replace NameValue with an ADT.
- Fix a reference counting bug 😓 
- Experiment with ADTs in the prelude (List, List1, Maybe).

Replace NameValue with an ADT.

---

bin/mirth0.c
src/prelude.mth
src/tests/test-blocks.mth

Implements `map` for lists and some other functions using blocks.

Implement some higher order words in prelude.

---

bin/mirth0.c
src/mirth/codegen.mth
src/tests/test-arithmetic.mth
src/tests/test-prelude.mth

Up until now we've used C's `a / b` operator, which has a sort of discontinuity at `a = 0`. This PR switches us to floor division, and the respective modulo operator, so that `(a / b) * b + (a % b) == a`. And adds a test.

Implement floor division and respective modulo.

---

bin/mirth0.c
src/mirth/codegen.mth
src/mirth/data/arrow.mth
src/mirth/elab.mth

This is a better approach for naming blocks, slightly more stable.

Nicer block numbering.

---

bin/mirth0.c
src/mirth/codegen.mth

Remove unnecessary CR filtering

---

bin/mirth0.c
src/mirth/codegen.mth
src/mirth/data/arrow.mth
src/mirth/elab.mth
src/mirth/mirth.h
src/tests/variable.mth

This PR tries to improve the handling of args and blocks. This results in nicer stack traces when using `dip`, `if`, and `while` with run args. Also adds the missing WORD_ENTER/WORD_EXIT on the C99 main function.

Handle args better & improve stack trace.

---

bin/mirth0.c
src/mirth/data/prim.mth
src/mirth/mirth.h
src/prelude.mth

Make `prim-mut-set` have the same type as `!`.

Fix prim-mut-set's type.

---

bin/mirth0.c
src/mirth/data/type.mth
src/prelude.mth
src/tests/test-unicode-strings.mth

This type isn't used right now.

Remove Char primitive type.

---

bin/mirth0.c
src/mirth/codegen.mth
src/mirth/data/type.mth
src/mirth/elab.mth
src/tests/resource-match.mth

Fixes the (pattern matching) unification bug detailed in #182. Adds a regression test.

Fix pattern matching in the presence of resources.

---

bin/mirth0.c
src/data/str.mth
src/mirth.mth
src/mirth/analysis/need.mth
src/mirth/codegen.mth
src/mirth/data/alias.mth
src/mirth/data/arrow.mth
src/mirth/data/prim.mth
src/mirth/elab.mth
src/mirth/lexer.mth
src/mirth/resource.mth
src/platform/posix.mth
src/prelude.mth
src/resource/buffer.mth
src/resource/file.mth
src/resource/input.mth
src/resource/output.mth

A bit more refactoring with resources.

Continue refactoring with resources.

---

Makefile
bin/mirth0.c
src/data/str.mth
src/mirth/analysis/need.mth
src/mirth/codegen.mth
src/mirth/mirth.h
src/prelude.mth
src/resource/buffer.mth
src/resource/input.mth
src/resource/output.mth
src/resource/set.mth

More resources stuff.

---

bin/mirth0.c
src/data/byte.mth
src/data/list.mth
src/data/str.mth
src/mirth.mth
src/mirth/codegen/c99.mth
src/mirth/codegen/mirth.h
src/mirth/data/ctx.mth
src/mirth/data/data.mth
src/mirth/data/name.mth
src/mirth/data/prim.mth
src/mirth/data/table.mth
src/mirth/data/token.mth
src/mirth/data/type.mth
src/mirth/elab.mth
src/mirth/lexer.mth
src/platform/posix.mth
src/prelude.mth
src/resource/array.mth
src/resource/buffer.mth
src/resource/file.mth
src/resource/input.mth
src/resource/output.mth
src/resource/set.mth
src/sdl2.mth
src/snake.mth
src/tests/test-is-directory.mth
src/tests/test-prelude.mth
src/tests/test-unicode-strings.mth

- Added the +Unsafe resource and the unsafe(...) word. Marked pointer operations unsafe.
- Created a Nat type (natural numbers, i.e. non-negative integers).
- Changed Size (non-negative number of bytes) into a newtype of Nat.
- Changed Offset (integer byte offset) into a newtype of Int.

Improving prelude type safety, added +Unsafe resource.

---

bin/mirth0.c
src/mirth-tests/error-alias-syntax-expected-argend.mth
src/mirth-tests/error-table-syntax-expected-argend.mth
src/mirth-tests/error-table-syntax-expected-no-args.mth
src/mirth-tests/error-table-syntax-expected-type-name-1.mth
src/mirth-tests/error-table-syntax-expected-type-name-2.mth
src/mirth/elab.mth

This PR makes syntax checking for `table(T)` stricter and adds tests.
Closes #196

Make table syntax parsing stricter.

---

bin/mirth0.c
src/args/parse.mth
src/args/types.mth
src/mirth/main.mth

This rewrites the argument parser to use labels and less tables

Refactor of argument parser to use new cleaner syntax

---

bin/mirth0.c
src/mirth-tests/error-type-name-resolution.mth
src/mirth/elab.mth
src/mirth/name.mth
src/std/either.mth
src/std/list.mth

This PR reworks the name resolution in types, to make it easier to extend to handle other sorts of name resolution.

Reworked type name resolution.

---

bin/mirth0.c
src/mirth-tests/error-type-name-resolution.mth
src/mirth/elab.mth
src/mirth/name.mth
src/mirth/token.mth

This PR adds support for qualified type names.
Closes #244.

Add support for qualified type names in type signatures.

---

bin/mirth0.c
src/mirth-tests/error-polymorphic-def-type.mth
src/mirth-tests/error-polymorphic-field-type.mth
src/mirth-tests/error-polymorphic-variable-type.mth
src/mirth/elab.mth

Prevents polymorphic types in field, variable and def-type declarations.
Fixes #197.

Prevent polymorphic field types.

---

src/snake/main.mth
src/snake/sdl2.mth

This wraps SDL_GetError and SDL_CreateWindow so they work properly again. Related to #253 (but doesn't fix the issue).

Fix the sdl2 bindings and snake.

---

bin/mirth0.c
lib/std/buffer.mth
lib/std/file.mth
lib/std/input.mth
lib/std/output.mth
lib/std/posix.mth
lib/std/set.mth
lib/std/str.mth
lib/std/test.mth
src/c99.mth
src/main.mth
src/need.mth

Lots of refactoring to take advantage of resource labels and value labels.

Use resource and value labels in compiler and std library.

---

bin/mirth0.c
src/c99.mth
src/mirth.h

This macro reduces the size of mirth0.c by about 10%.

Use a C macro for string literals.

---

.vscode/tasks.json
test/external-labelled-argument.mth
tools/build.sh

A build script to control better what happens when you build a file in this project, in vscode.
Also adds a test for labelled exception arguments.

Add a little build script

---

.github/workflows/build.yml
Makefile
bin/mirth0.c
examples/hello.mth
examples/sdl2.mth
examples/snake-infer-types.mth
lib/arg-parser/parse.mth
lib/std/buffer.mth
lib/std/ctypes.mth
lib/std/str.mth
src/name.mth
tools/build-examples.sh
tools/build.sh

Updates examples to use new def syntax. Also adds a version of snake with no type annotations, just to prove that it's possible.

Use new syntax in examples.

---

bin/mirth0.c
src/c99.mth
src/elab.mth
src/mirth.h
src/table.mth
src/type.mth

This PR removes the table size limit & reduces field memory usage in general ... at the cost of an extra indirection.

Reimplement table fields.

---

bin/mirth0.c
lib/std/file.mth
lib/std/path.mth
lib/std/prelude.mth
lib/std/world.mth

very small refactoring:
- move the path separator functions into OS
- move running-os and running-arch into +World

refactor Path & OS functions

---

src/main.mth

Rewrite of the pretty printer for arguments to use the new default parameters.

Clean up pretty printing of arguments

---

lib/std/prelude.mth
lib/std/unicode.mth
test/std-unicode.mth

There's a lot missing here (particularly stuff that verifies your unicode instead of unsafely assuming validity), but this is a good baseline that's easy to build other features on top of.
Probably some code style issues, feel free to either fix them up or point them out to me.

Add some unicode codepoint support

---

bin/mirth0.c
src/elab.mth
src/token.mth
test/error-default-word-param.mth

Reports errors encountered during the elaboration of default parameters at the caller's location, not at the definition.
Fixes #338 somewhat, although the error messages might still not be the best.

Improve default parameter errors.

---

bin/mirth0.c
src/elab.mth
src/typedef.mth
src/var.mth
test/data-params.mth

Adds support for `+a` resource and `*a` stack type parameters to type constructors.
Fixes #246

Support resource and stack type parameters in types.

---

bin/mirth0.c
lib/std/byte.mth
lib/std/either.mth
lib/std/file.mth
lib/std/maybe.mth
lib/std/result.mth
src/c99.mth
src/elab.mth
src/lexer.mth

This PR takes advantage of the new resource type paramaters to add +Maybe, +Either, Result and +Result, and uses them in some places.

Use resource params in std lib and compiler.

---

bin/mirth0.c
src/lexer.mth
src/token.mth

This should fix #240, though it doesn't actually do anything with the doc comments yet.

Attach doc comments to the next token

---

bin/mirth0.c
src/c99.mth
src/mirth.h
src/version.mth
test/big-int.mth

Also adds a test for big ints.

Multiplication and >Str for big ints.

---

bin/mirth0.c
lib/std/map.mth
src/arrow.mth
src/c99.mth
src/data.mth
src/elab.mth
src/specializer.mth
src/type.mth
src/var.mth

Keep track of the kinds of metavariables.

Track metavariable kinds.
